#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "SkillProof — Railway production deployment (ticket 04)"

say "This provisions the real infrastructure ticket 04 needs: a Railway project"
say "building from this repo's Dockerfile, a Postgres addon, a dedicated"
say "production GitHub OAuth App, a RAILWAY_TOKEN GitHub Actions secret, and"
say "every production env var set directly in Railway's dashboard (never in"
say "this repo)."
note "Nothing here touches your local .env or the local-dev GitHub OAuth App."

# ── Stage 1: Railway project from this repo ────────────────────────────────
stage "Railway — create the project"
say "Ticket 01/02/03 already made the repo deployable: DATABASE_URL handles"
say "Railway's Postgres, the Dockerfile builds the app, and CI has a deploy"
say "job wired to a RAILWAY_TOKEN secret. This stage creates the Railway"
say "project those already point at."
open_url "https://railway.app/new"
step "Choose 'Deploy from GitHub repo' and select Pratham-204/SkillProof."
step "If Railway asks to install the Railway GitHub App on the repo, allow it."
step "Once the project exists, open the new service → Settings → Build and"
step "  confirm the Builder is set to 'Dockerfile' (not Nixpacks) — this repo"
step "  ships a Dockerfile specifically so Railway doesn't have to guess."
note "The first build will likely fail or sit idle until env vars are set in"
note "stage 5 below — that's expected, don't troubleshoot it yet."
confirm "Project created and Builder set to Dockerfile?" || warn "come back to this before continuing"

# ── Stage 2: claim the skillproof.up.railway.app subdomain ─────────────────
stage "Railway — claim the skillproof subdomain"
say "The production OAuth callback and CI's smoke expectations are pinned to"
say "https://skillproof.up.railway.app — this has to be the exact domain."
step "In the service → Settings → Networking, generate a public domain if one"
step "  doesn't exist yet."
step "Railway usually assigns a random *.up.railway.app subdomain first — look"
step "  for an edit (pencil) icon on the generated domain to rename the"
step "  subdomain portion to 'skillproof'."
note "Railway's exact UI for renaming a generated domain has moved before —"
note "if there's no obvious rename control, check Railway's current docs for"
note "'custom subdomain' rather than assuming this exact path still exists."
warn "If 'skillproof' is already taken by someone else on Railway, you'll need a"
warn "different subdomain — and must then update the OAuth callback URL below"
warn "and README's deployment checklist to match, instead of skillproof.up.railway.app."
confirm "Service is reachable at exactly https://skillproof.up.railway.app?" || warn "come back to this before continuing"

# ── Stage 3: attach Postgres ────────────────────────────────────────────────
stage "Railway — attach Postgres"
say "db.py's make_engine() already normalizes whatever DATABASE_URL Railway"
say "injects here (postgres:// → postgresql+psycopg://) — ticket 01."
step "In the same Railway project, click '+ New' → Database → Add PostgreSQL."
step "Open the app service's Variables tab and confirm DATABASE_URL now shows"
step "  up (Railway usually auto-injects a reference variable pointing at the"
step "  new Postgres addon within the same project; if it's not there, add it"
step "  yourself as a reference to the Postgres service's DATABASE_URL)."
confirm "DATABASE_URL is present on the app service, pointing at the new Postgres addon?" || warn "come back to this before continuing"

# ── Stage 4: production GitHub OAuth App ────────────────────────────────────
stage "GitHub — register the production OAuth App"
say "This must be a brand-new OAuth App, separate from local dev's. Don't"
say "reuse or edit the existing local-dev app."
open_url "https://github.com/settings/applications/new"
step "Application name: something like 'SkillProof (production)'."
step "Homepage URL: https://skillproof.up.railway.app"
step "Authorization callback URL: https://skillproof.up.railway.app/auth/github/callback"
step "Register the application."
step "On the app's page, copy the Client ID, then click 'Generate a new client"
step "  secret' and copy that too."
note "Keep this tab open — you'll paste both values into Railway in the next stage."
pause "Copied the Client ID and Client Secret?"

# ── Stage 5: production env vars in Railway ─────────────────────────────────
stage "Railway — set every production env var"
say "config.py's _resolve_production_defaults refuses to boot in production"
say "without a real SKILLPROOF_TOKEN_ENCRYPTION_KEY, so this key can't be"
say "skipped or left to the dev-only auto-generated fallback."
say "Generating a fresh Fernet key locally (never reused from any dev key):"
GEN_KEY=""
for PY in .venv/Scripts/python.exe .venv/bin/python python3 python; do
  if command -v "$PY" >/dev/null 2>&1; then
    # The `if OUT=$(...); then` form (not `CMD=$(...) && ...`) keeps this
    # failure-tolerant under `set -e`: a failing command substitution is only
    # exempted from -e when it sits in an if/elif test position — chained
    # with && instead, a failure here would abort the whole wizard.
    if OUT=$("$PY" -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null); then
      GEN_KEY="$OUT"
      break
    fi
  fi
done
if [[ -n "$GEN_KEY" ]]; then
  printf '  %s%s%s\n' "$BOLD" "$GEN_KEY" "$RESET"
  note "(generated locally — this is shown once; if you lose it, just re-run this stage)"
else
  warn "couldn't generate a key locally (no python with 'cryptography' on PATH)"
  step "Generate one yourself: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
fi
say ""
say "In Railway, open the app service → Variables, and add each of these:"
step "SKILLPROOF_ENVIRONMENT = production"
step "SKILLPROOF_GITHUB_CLIENT_ID = <the Client ID from stage 4>"
step "SKILLPROOF_GITHUB_CLIENT_SECRET = <the Client Secret from stage 4>"
step "SKILLPROOF_GITHUB_OAUTH_REDIRECT_URI = https://skillproof.up.railway.app/auth/github/callback"
step "SKILLPROOF_TOKEN_ENCRYPTION_KEY = <the key generated above>"
step "SKILLPROOF_GROQ_API_KEY = <copy the value from your local .env — same key, reused>"
note "None of these six values are ever written to this repo or committed."
confirm "All six variables set in Railway, and the service redeployed?" || warn "come back to this before continuing"

# ── Stage 6: RAILWAY_TOKEN → GitHub Actions secret ──────────────────────────
stage "Railway → GitHub — wire up RAILWAY_TOKEN"
say "ci.yml's deploy job (ticket 03) already reads secrets.RAILWAY_TOKEN — it"
say "just needs the secret to actually exist."
open_url "https://railway.app/dashboard"
step "Open the SkillProof project → Settings → Tokens, and create a"
step "  project-scoped token (preferred — scoped to just this project)."
note "If your Railway plan/version doesn't show Tokens under project Settings,"
note "check Account Settings → Tokens instead for an account-wide token."
step "Copy the generated token now — Railway will not show it again."
ask_secret RAILWAY_TOKEN "Paste the Railway token:"
set_secret RAILWAY_TOKEN "$RAILWAY_TOKEN"

# ── Stage 7: verify end to end ──────────────────────────────────────────────
stage "Verify the whole pipeline"
say "This is the real test: push to main → CI tests → deploy job → Railway"
say "build → live production OAuth login."
step "Push any commit to main (or trigger a manual redeploy in Railway) and"
step "  watch the GitHub Actions run: backend + frontend jobs, then deploy."
open_url "https://skillproof.up.railway.app"
step "Once deployed, confirm the page loads and 'Connect GitHub' completes a"
step "  full login using the production OAuth App from stage 4."
confirm "Production deploy is live and GitHub login works end to end?" || warn "come back to this once the pipeline has run"

finish
note "Ticket 04's acceptance criteria are all human-side actions — mark it"
note "done in .scratch/skillproof-deployment/issues/04-provision-railway-oauth-secrets.md"
note "yourself once you've confirmed everything above."
