"""baseline

Revision ID: 76f68d902eb6
Revises: 
Create Date: 2026-09-07 11:41:15.199371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f68d902eb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('github_user_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('github_token_encrypted', sa.Text(), nullable=False),
    sa.Column('needs_reconnect', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidates_github_user_id'), 'candidates', ['github_user_id'], unique=True)
    op.create_table('sighting_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem', 'package_name', name='uq_sighting_decision')
    )
    op.create_table('candidate_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_candidate_sessions_candidate_id'), 'candidate_sessions', ['candidate_id'], unique=False)
    op.create_table('evidence_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_commits', sa.JSON(), nullable=False),
    sa.Column('temporal_span_days', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_is_fallback', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill', 'taxonomy_version', name='uq_candidate_skill_taxonomy_version')
    )
    op.create_index(op.f('ix_evidence_cards_candidate_id'), 'evidence_cards', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evidence_cards_skill'), 'evidence_cards', ['skill'], unique=False)
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem', 'package_name', 'candidate_id', 'repo', name='uq_sighting_candidate_repo')
    )
    op.create_index(op.f('ix_sightings_candidate_id'), 'sightings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_sightings_ecosystem'), 'sightings', ['ecosystem'], unique=False)
    op.create_index(op.f('ix_sightings_package_name'), 'sightings', ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sightings_package_name'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_ecosystem'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_candidate_id'), table_name='sightings')
    op.drop_table('sightings')
    op.drop_index(op.f('ix_evidence_cards_skill'), table_name='evidence_cards')
    op.drop_index(op.f('ix_evidence_cards_candidate_id'), table_name='evidence_cards')
    op.drop_table('evidence_cards')
    op.drop_index(op.f('ix_candidate_sessions_candidate_id'), table_name='candidate_sessions')
    op.drop_table('candidate_sessions')
    op.drop_table('sighting_decisions')
    op.drop_index(op.f('ix_candidates_github_user_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
